default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: dogs
  username: root
  password: rails
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
